name: Build and Deploy GitBook

on:
  push:
    branches:
      - main  # Thay thế "main" bằng tên nhánh chính của bạn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build GitBook
        run: npx gitbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book  # Thay thế bằng thư mục xuất bản của GitBook

